GENERAL:
  task: train  # train, test
  manual_seed: 123
  model_dir: model/pointgroup/pointgroup.py
  dataset_dir: data/alivev1_inst.py
  exp_path: 'exp/alivev1/pointgroup/pointgroup_alive/regression/trial_n1e'

DATA:
  data_root: dataset
  dataset: alivev1
  filename_suffix: .pickle

  classes: 2
  ignore_label: -100

  input_channel: 3
  scale: 50   # voxel_size = 1 / scale, scale 50(2cm)
  batch_size: 2
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean

STRUCTURE:
  model_name: robotNet
  m: 16 # 16 or 32
  block_residual: True
  block_reps: 2
  fc1_hidden: 8192 #Number of hidden layers in layer 1
  fc2_hidden: 4096 #Number of hidden layers in layer 2
  regres_dim: 7    #Number of regression values
  use_coords: True
  max_point_lim: 512

TRAIN:
  epochs: 1200
  train_workers: 16 # data loader workers
  optim: Adam # Adam or SGD
  lr: 0.001
  regression_lr: 0.001
  step_epoch: 120 #Should same with epochs
  multiplier: 0.5
  momentum: 0.9
  weight_decay: 0.0001
  save_freq: 32  # also eval_freq
  loss_weight: [1.0, 1.0, 1.0, 1.0] # semantic_loss, offset_norm_loss, offset_dir_loss, score_loss

  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50 # the minimal voxel size is 2cm
  score_fullscale: 14
  score_mode: 4 # mean

  pretrain_path:
  pretrain_module: []
  fix_module: []

GROUP:
  ### point grouping
  cluster_radius: 0.03
  cluster_meanActive: 50
  cluster_shift_meanActive: 300
  cluster_npoint_thre: 50

  prepare_epochs: 401 #prepare_epochs: 128

TEST:
  split: test
  test_epoch: 10
  test_workers: 16
  test_seed: 567

  TEST_NMS_THRESH: 0.3
  TEST_SCORE_THRESH: 0.09
  TEST_NPOINT_THRESH: 100

  eval: False
  eval_alive: True
  save_semantic: True
  save_pt_offsets: True
  save_instance: True